name: tests

on:
  push:
    paths:
    - 'src/**.py'
    - 'tests/**.py'
    - 'scripts/**'

jobs:
  apply:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python: [3.7.17, 3.8.17, 3.9.17, 3.10.12, 3.11.4]

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python ${{ matrix.python }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python }}

    - name: install
      run: ./scripts/ci.sh install-test

    - name: run-test
      run: ./scripts/ci.sh run-test
